import * as header from './js/header.js';
import * as hero from './js/hero.js';
import * as aboutMe from './js/about-me.js';
import * as benefits from './js/benefits.js';
import * as projects from './js/project.js';
import * as faq from './js/faq.js';
import * as covers from './js/covers.js';
import * as reviews from './js/reviews.js';
import * as workTogether from './js/work-together.js';